[package]
name = "renegadex_patcher"
version = "0.1.0"
authors = ["SonnyX"]
edition = "2018"

[dependencies]
json = "0.12"
sha2 = "0.9"
hex = "0.4"
rust-ini = "0.16"
rayon = "1.2"
rand = "0.7"
xdelta = { git = "https://github.com/SonnyX/xdelta-decoder-rust.git" }
num_cpus = "1.11"
hyper = "0.13"
hyper-tls = "0.4"
native-tls = "0.2"
http = "0.2"
tokio = { version = "0.3", features = ["full"] }
url = "2.1"
futures = "0.3"
http-body = "0.3"
tower = "0.3"
tokio-tls = "0.3"
runas = { git = "https://github.com/SonnyX/rust-runas.git" }
log = "0.4"

[profile.test]
opt-level = 3
debug = 2

[profile.dev]
opt-level = 3
debug = true
